### ISSUE TITLE
Typo in a comment

### ISSUE THREAD

**Issue by manualvarado22** [gaboroa14/MetodosNumericosSistemasdeEcuaciones#1]
I wanted to learn a bit more about the Gaus-Jordan method, but a typo in a comment made it impossible for me to continue reading the code.

The typo in question is in the line 14, in CodigosSistEcuacionesGabrielRoa.R

Please fix the typo so I can continue reading the code.

**Comment by gaboroa14** [comment]
Fixed. Thank you for your patience!
